"""
1、UI自动化测试框架时使用appium，用到appium-python-client这个库
2、自动化测试框架使用pytest，用到pytest这个库及pytest排序（pytest-ordering）、失败重跑（pytest-rerunfailures）、执行进度（pytest-sugar）等库
3、测试报告生成使用allure相关库
4、对信息娱乐系统测试过程中，有时需要收集和判断串口输出的日志，使用serial这个库
5、信息娱乐系统现在大多使用android系统，在界面有动画的时候控件基本是无法抓取，此时使用图片识别去判断界面，使用opencv-python这个库的模板匹配和特征匹配来判断。
6、测图库和视频模块时，需要生成纯色图片和视频方便判断图片，使用pillow这个库去生成纯色图片
7、测USB插拔时，操作机械手使用pymodbus库
8、测智能语音模块时，需要播放录音唤醒语音助手，使用pyaudio库
9、进行web后端接口测试时，使用requests库进行接口请求，使用json库解析返回的json信息
10、为方便调试和保存我们脚本的执行日志，使用colorlog这个库
"""
